import { Typography } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import AppHeader from "../src/components/AppHeader";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader></AppHeader>
      <Box>
        <Typography sx={{ fontWeight: "bold" }}>
          HELLO IT People Ltd.
        </Typography>
      </Box>
    </>
  );
}
