import { Typography } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import AppHeader from "../src/components/AppHeader";
import styles from "../styles/Home.module.css";
import SignInSide from "./signin";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wisebox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignInSide />
      {/* <AppHeader></AppHeader> */}
      {/* <Box>
        <Typography variant="h4" sx={{ fontWeight: "bold", textAlign: "center", marginTop: "50px" }}>
          Hello Wisebox.
        </Typography>
      </Box> */}
    </>
  );
}
